//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsConsumirJava.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mipaquete/", ConfigurationName="ServiceReference1.NewWebService")]
    public interface NewWebService {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento name del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://mipaquete/NewWebService/helloRequest", ReplyAction="http://mipaquete/NewWebService/helloResponse")]
        WindowsFormsConsumirJava.ServiceReference1.helloResponse hello(WindowsFormsConsumirJava.ServiceReference1.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mipaquete/NewWebService/helloRequest", ReplyAction="http://mipaquete/NewWebService/helloResponse")]
        System.Threading.Tasks.Task<WindowsFormsConsumirJava.ServiceReference1.helloResponse> helloAsync(WindowsFormsConsumirJava.ServiceReference1.helloRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ci del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://mipaquete/NewWebService/obtenermateriasRequest", ReplyAction="http://mipaquete/NewWebService/obtenermateriasResponse")]
        WindowsFormsConsumirJava.ServiceReference1.obtenermateriasResponse obtenermaterias(WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mipaquete/NewWebService/obtenermateriasRequest", ReplyAction="http://mipaquete/NewWebService/obtenermateriasResponse")]
        System.Threading.Tasks.Task<WindowsFormsConsumirJava.ServiceReference1.obtenermateriasResponse> obtenermateriasAsync(WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hello", Namespace="http://mipaquete/", Order=0)]
        public WindowsFormsConsumirJava.ServiceReference1.helloRequestBody Body;
        
        public helloRequest() {
        }
        
        public helloRequest(WindowsFormsConsumirJava.ServiceReference1.helloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public helloRequestBody() {
        }
        
        public helloRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="helloResponse", Namespace="http://mipaquete/", Order=0)]
        public WindowsFormsConsumirJava.ServiceReference1.helloResponseBody Body;
        
        public helloResponse() {
        }
        
        public helloResponse(WindowsFormsConsumirJava.ServiceReference1.helloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class helloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public helloResponseBody() {
        }
        
        public helloResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenermateriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenermaterias", Namespace="http://mipaquete/", Order=0)]
        public WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequestBody Body;
        
        public obtenermateriasRequest() {
        }
        
        public obtenermateriasRequest(WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class obtenermateriasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ci;
        
        public obtenermateriasRequestBody() {
        }
        
        public obtenermateriasRequestBody(string ci) {
            this.ci = ci;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenermateriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenermateriasResponse", Namespace="http://mipaquete/", Order=0)]
        public WindowsFormsConsumirJava.ServiceReference1.obtenermateriasResponseBody Body;
        
        public obtenermateriasResponse() {
        }
        
        public obtenermateriasResponse(WindowsFormsConsumirJava.ServiceReference1.obtenermateriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class obtenermateriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public obtenermateriasResponseBody() {
        }
        
        public obtenermateriasResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NewWebServiceChannel : WindowsFormsConsumirJava.ServiceReference1.NewWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NewWebServiceClient : System.ServiceModel.ClientBase<WindowsFormsConsumirJava.ServiceReference1.NewWebService>, WindowsFormsConsumirJava.ServiceReference1.NewWebService {
        
        public NewWebServiceClient() {
        }
        
        public NewWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NewWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NewWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsConsumirJava.ServiceReference1.helloResponse WindowsFormsConsumirJava.ServiceReference1.NewWebService.hello(WindowsFormsConsumirJava.ServiceReference1.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WindowsFormsConsumirJava.ServiceReference1.helloRequest inValue = new WindowsFormsConsumirJava.ServiceReference1.helloRequest();
            inValue.Body = new WindowsFormsConsumirJava.ServiceReference1.helloRequestBody();
            inValue.Body.name = name;
            WindowsFormsConsumirJava.ServiceReference1.helloResponse retVal = ((WindowsFormsConsumirJava.ServiceReference1.NewWebService)(this)).hello(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsConsumirJava.ServiceReference1.helloResponse> WindowsFormsConsumirJava.ServiceReference1.NewWebService.helloAsync(WindowsFormsConsumirJava.ServiceReference1.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsConsumirJava.ServiceReference1.helloResponse> helloAsync(string name) {
            WindowsFormsConsumirJava.ServiceReference1.helloRequest inValue = new WindowsFormsConsumirJava.ServiceReference1.helloRequest();
            inValue.Body = new WindowsFormsConsumirJava.ServiceReference1.helloRequestBody();
            inValue.Body.name = name;
            return ((WindowsFormsConsumirJava.ServiceReference1.NewWebService)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsConsumirJava.ServiceReference1.obtenermateriasResponse WindowsFormsConsumirJava.ServiceReference1.NewWebService.obtenermaterias(WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequest request) {
            return base.Channel.obtenermaterias(request);
        }
        
        public string obtenermaterias(string ci) {
            WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequest inValue = new WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequest();
            inValue.Body = new WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequestBody();
            inValue.Body.ci = ci;
            WindowsFormsConsumirJava.ServiceReference1.obtenermateriasResponse retVal = ((WindowsFormsConsumirJava.ServiceReference1.NewWebService)(this)).obtenermaterias(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsConsumirJava.ServiceReference1.obtenermateriasResponse> WindowsFormsConsumirJava.ServiceReference1.NewWebService.obtenermateriasAsync(WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequest request) {
            return base.Channel.obtenermateriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsConsumirJava.ServiceReference1.obtenermateriasResponse> obtenermateriasAsync(string ci) {
            WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequest inValue = new WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequest();
            inValue.Body = new WindowsFormsConsumirJava.ServiceReference1.obtenermateriasRequestBody();
            inValue.Body.ci = ci;
            return ((WindowsFormsConsumirJava.ServiceReference1.NewWebService)(this)).obtenermateriasAsync(inValue);
        }
    }
}
